# Generated by Django 2.2 on 2019-04-25 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsuarioEquipe',
        ),
    ]
