# Generated by Django 2.2.2 on 2019-06-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_auto_20190624_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='quantidadeDeVagas',
            field=models.IntegerField(default=100),
        ),
    ]
