# Generated by Django 2.2.2 on 2019-06-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_auto_20190624_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representante', to=settings.AUTH_USER_MODEL),
        ),
    ]
